### PR TITLE
Main_Widget: Add tooltips wo selection icons

### PR DESCRIPTION
**Pull request by Rosi2143**
First small functional change to add tooltips

This is useful for PC to see what the meating of the icons is.

Signed-off-by: Rosi2143 <Schrott.Micha@web.de>

### CODE REVIEW

**Comment by hmerk** [comment]
Thanks, but I don‘t understand this one.
The tooltips just show the same text as the label of the badges.
And what about the .bak file ? Purpose?

**Comment by Rosi2143** [comment]
On my PC (Windows11 + Firefox) the name is often not seen - if I do not scroll up.

So I thought it's a nice idea to also have a tooltip that appears on top of the icon.

See image: Screenshot 2022-11-26 104536

**Comment by Rosi2143** [comment]
Sorry the *.bak file as an error - it's removed now.

**Comment by hmerk** [comment]
Hm, we are developing this with focus on small mobile devices, therefore I don‘t see the need for this.

**Comment by Rosi2143** [comment]
OK - accepted

**Pull request closed without merging**
