### PR TITLE
new MainWidgetPresence_Card

### PR DESCRIPTION
**Pull request by Rosi2143**
Add a card to display who is currently present.

Same base as the SceneCard and same config options

Signed-off-by: Rosi2143 <Schrott.Micha@web.de>

### CODE REVIEW

**Comment by hmerk** [comment]
Please do not just add new cards with a PR but first open an issue with a feature request to discuss if this is something to add to the project. Furthermore the styling of your card does not fit our styleguide.

**Comment by hmerk** [comment]
Please don‘t comit changes for different widgets here. I would prefer single PRs for every widget.
And please do not reorder my repeater code.
Even the suggestion in editor is ordered different, how I coded is more logical and better to read.

I need to check your changes and see how it looks like.
Better to post a screenshot when making additions.

**Comment by Rosi2143** [comment]
Sorry - that was not intended to be merged.
I pushed it to the wrong branch.

**Comment by hmerk** [comment]
😉👍

**Pull request closed without merging**
