### PR TITLE
add draft version of readme in root

### PR DESCRIPTION
**Pull request by Rosi2143**
README: Add a first draft version of the readme file 

* explain the intention and basic ideas of the project
* add links to all sub-readme files
* add an images folder

Signed-off-by: Rosi2143 <Schrott.Micha@web.de>

### CODE REVIEW

**Comment by Rosi2143** [comment]
Hi @hmerk,

I've just seen that you created new content in [mainWidget/readme](https://github.com/hmerk/main_widget/blob/main/mainWidget/Readme.md) already.

I will check this and upload a new changeset.

Sorry.

**Comment by hmerk** [comment]
Small comments here:
overview picture shows weather card but should show menu as well
openPage.md contains information on  floor and room items, but should not.

**Comment by hmerk** [comment]
Thanks, looks good, apart from the screenshot for main_widget.
You are not using the default color scheme.

**Comment by Rosi2143** [comment]
Sorry - I missed that I experimented a bit with the color schemes.

Thanks for the hint.

**Comment by hmerk** [comment]
Thanks, LGTM.

**Pull request merged**
