### PR TITLE
WeatherCard: Use default values to simplify selection logic

### PR DESCRIPTION
**Pull request by Rosi2143**
Instead of having to check for each attribute if an config value is defined now default values are used - with the same value used as before if nothing has been defined.

Signed-off-by: Rosi2143 <Schrott.Micha@web.de>

### CODE REVIEW

**Comment by hmerk** [comment]
default: does not work when installing via Marketplace.
It needs to be defaultValue:

Generally, I do want to get rid of this widget, as it is already published in the marketplace.
I prefer to just inject the needed config and use the „stock“ version.

**Comment by Rosi2143** [comment]
Hi @hmerk, you keep refering to a "marketplace version" - but I can
t find it.
Neither [in OH3 itself](http://openhabian3:8080/settings/addons) nor in the [community pages](https://community.openhab.org/c/marketplace/ui-widgets/75).

I find e.g. this page in the [marketplace](https://community.openhab.org/c/marketplace/ui-widgets/75) for the [weather widget](https://community.openhab.org/t/oh3-main-ui-main-widget-part-2-the-weather-card/138813/6), but there you mentioned that I should not comment here but that "``The weather widget has a separate marketplace topic.``".

Can you please provide the link?

**Comment by hmerk** [comment]
here it is
https://community.openhab.org/t/ui-widget-weather/106842

Sorry for confusing, it is not in the marketplace

**Comment by Rosi2143** [comment]
OK - I'll check with https://community.openhab.org/t/ui-widget-weather/106842

**Comment by Rosi2143** [comment]
closed

**Pull request closed without merging**
